name: "CI - Lint for Pull Requests"

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'general/**/*.md'
      - .markdownlint-cli2.cjs

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint markdown files
        run: yarn mdlint-all
